### ISSUE TITLE
error before install

### ISSUE THREAD

**Issue by 0x4171341** [its-joseph-230606/LlamaGPT#2]
Hello, after the installation, when I run the python chat.py script it asks me the question and when I write to it the program breaks

**Comment by its-joseph-230606** [comment]
Ok . This is because Model is overloaded.

**Comment by its-joseph-230606** [comment]
Thanks for the note. This project uses the Llama2 model of Hugging Face. It is overloaded due to many people using this model now. Can you solve it?

**Comment by 0x4171341** [comment]
I'll try, is there a development branch other than main, master?

**Comment by its-joseph-230606** [comment]
> I'll try, is there a development branch other than main, master?

Yes , dev branch
